/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.4.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as comments_get from "../comments/get.js";
import type * as comments_puts from "../comments/puts.js";
import type * as notes_get from "../notes/get.js";
import type * as notes_put from "../notes/put.js";
import type * as tags_get from "../tags/get.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "comments/get": typeof comments_get;
  "comments/puts": typeof comments_puts;
  "notes/get": typeof notes_get;
  "notes/put": typeof notes_put;
  "tags/get": typeof tags_get;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
